apiVersion: apps/v1
kind: Deployment
metadata:
  name: noop-deployment
spec:
  selector:
    matchLabels:
      app: noop
  replicas: 1
  template:
    metadata:
      labels:
        app: noop
    spec:
      containers:
      - name: noop
        image: proskeh/noop:0.1
        ports:
        - containerPort: 80
